/**:
  ros__parameters:
    joint_limits:
      arm_joint_1:
        has_velocity_limits: true
        max_velocity: 1.0
        has_acceleration_limits: true
        max_acceleration: 2.0
      arm_joint_2:
        has_velocity_limits: true
        max_velocity: 1.0
        has_acceleration_limits: true
        max_acceleration: 2.0
      arm_joint_3:
        has_velocity_limits: true
        max_velocity: 1.0
        has_acceleration_limits: true
        max_acceleration: 2.0
      arm_joint_4:
        has_velocity_limits: true
        max_velocity: 1.5
        has_acceleration_limits: true
        max_acceleration: 3.0
      arm_joint_5:
        has_velocity_limits: true
        max_velocity: 1.5
        has_acceleration_limits: true
        max_acceleration: 3.0
      arm_joint_6:
        has_velocity_limits: true
        max_velocity: 2.0
        has_acceleration_limits: true
        max_acceleration: 4.0
      gripper_left_joint:
        has_velocity_limits: true
        max_velocity: 0.1
        has_acceleration_limits: true
        max_acceleration: 0.5
